# This workflow will build a calculator app
name: calculator-pull-request
on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Run Tests
        run: npm test
  version:
      needs: build
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - run: git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
        - run: git config user.name "$GITHUB_ACTOR"
        - run: npm version minor -m "v%s"
        - run: VERSION=$(node -p "require('./package.json').version")
        - run: git tag ${VERSION}
        - run: echo HEAD:${{ github.head_ref }}
        - run: git pull origin main
        - run: git push "https://$GITHUB_ACTOR:${{ secrets.ACCESS_TOKEN }}@github.com/$GITHUB_REPOSITORY.git" HEAD:${{ github.head_ref }} --tags
        - run: git push "https://$GITHUB_ACTOR:${{ secrets.ACCESS_TOKEN }}@github.com/$GITHUB_REPOSITORY.git" HEAD:${{ github.head_ref }} --follow-tags
